# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff6fcb6578a566f51492fa1dc785c0ce5d64bdd51a176120bda788663ac5d97d5a5e63dd0833aa61ac2b027f3885ed330046d10646604650da6f5299e8c3baf

test:
  secret_key_base: 04b5bb12c888db90f340849ea4a4c75ae92f46507b0e0bd8f894c82b55398ec5bf46cc8a63ffdcdcbf0f225b2bc84794b6e221daaaf26f231a064923a62935a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
